"""Board CLI service — generates the shell script agents use to communicate.

The board CLI is a lightweight shell wrapper around Draft's message board API.
It gets injected into each agent's worktree at `.draft/board-cli.sh` and uses
environment variables for routing (board_id, ticket_id, session_id).
"""

import logging
import stat
from pathlib import Path
from textwrap import dedent

logger = logging.getLogger(__name__)

# The port Draft backend listens on (default 8000)
DEFAULT_API_PORT = 8000


def generate_board_cli_script(
    api_base_url: str = "http://localhost:8000",
) -> str:
    """Generate the board CLI shell script content.

    The script reads DRAFT_BOARD_ID, DRAFT_TICKET_ID, and DRAFT_SESSION_ID
    from environment variables (set when launching the tmux session).
    """
    return dedent(f"""\
        #!/usr/bin/env bash
        # Draft Board CLI — inter-agent message board
        # Auto-generated by Draft. Do not edit.
        set -uo pipefail

        API="{api_base_url}"
        BOARD_ID="${{DRAFT_BOARD_ID:?DRAFT_BOARD_ID not set}}"
        TICKET_ID="${{DRAFT_TICKET_ID:?DRAFT_TICKET_ID not set}}"
        SESSION_ID="${{DRAFT_SESSION_ID:?DRAFT_SESSION_ID not set}}"
        ROLE="${{DRAFT_AGENT_ROLE:-unknown}}"
        MAX_RETRIES=3

        usage() {{
            echo "Usage: board <command> [args]"
            echo ""
            echo "Commands:"
            echo "  post <message>   Post a message to the team board"
            echo "  read             Read new messages since your last read"
            echo "  check            Check how many unread messages you have"
            echo "  team             List team members on this board"
            echo "  all              Show all messages (full history)"
            echo ""
            echo "Environment:"
            echo "  DRAFT_BOARD_ID   = $BOARD_ID"
            echo "  DRAFT_TICKET_ID  = $TICKET_ID"
            echo "  DRAFT_SESSION_ID = $SESSION_ID"
            echo "  DRAFT_AGENT_ROLE = $ROLE"
        }}

        # Retry wrapper for curl calls
        api_call() {{
            local method="$1" url="$2"
            shift 2
            local attempt=0
            while [ $attempt -lt $MAX_RETRIES ]; do
                if result=$(curl -sf --connect-timeout 5 --max-time 15 -X "$method" "$url" "$@" 2>/dev/null); then
                    echo "$result"
                    return 0
                fi
                attempt=$((attempt + 1))
                if [ $attempt -lt $MAX_RETRIES ]; then
                    sleep 1
                fi
            done
            echo "ERROR: API call failed after $MAX_RETRIES attempts: $method $url" >&2
            return 1
        }}

        case "${{1:-help}}" in
            post)
                shift
                MESSAGE="$*"
                if [ -z "$MESSAGE" ]; then
                    echo "Error: message content required"
                    echo "Usage: board post <message>"
                    exit 1
                fi
                # Use a temp file for the JSON body to handle special characters
                TMPFILE=$(mktemp 2>/dev/null || echo "/tmp/board_msg_$$")
                if ! python3 -c "import json,sys; json.dump(dict(ticket_id='$TICKET_ID',session_id='$SESSION_ID',sender_role='$ROLE',content=sys.argv[1]),open('$TMPFILE','w'))" "$MESSAGE" 2>/dev/null; then
                    # Fallback: write JSON manually for simple messages
                    printf '{{"ticket_id":"%s","session_id":"%s","sender_role":"%s","content":"%s"}}' \
                        "$TICKET_ID" "$SESSION_ID" "$ROLE" "$MESSAGE" > "$TMPFILE"
                fi
                api_call POST "$API/boards/$BOARD_ID/messages" \
                    -H "Content-Type: application/json" \
                    -d @"$TMPFILE" | python3 -c "
        import json,sys
        try:
            m = json.load(sys.stdin)
            print(f'[{{m.get(\"sender_role\",\"?\")}}] Message posted (id={{m.get(\"id\",\"?\")}})')
        except: print('Message posted')
        " 2>/dev/null || echo "Message posted (response parse skipped)"
                rm -f "$TMPFILE"
                ;;

            read)
                api_call GET "$API/boards/$BOARD_ID/messages?ticket_id=$TICKET_ID&session_id=$SESSION_ID" | python3 -c "
        import json,sys
        try:
            msgs = json.load(sys.stdin)
            if not msgs:
                print('No new messages.')
            else:
                for m in msgs:
                    role = m.get('sender_role', '?')
                    content = m.get('content', '')
                    print(f'[{{role}}]: {{content}}')
                print(f'--- {{len(msgs)}} new message(s) ---')
        except Exception as e:
            print(f'Error reading messages: {{e}}')
        " 2>/dev/null || echo "No new messages (API unreachable)."
                ;;

            check)
                api_call GET "$API/boards/$BOARD_ID/messages/check?ticket_id=$TICKET_ID&session_id=$SESSION_ID" | python3 -c "
        import json,sys
        try:
            data = json.load(sys.stdin)
            n = data.get('unread', 0)
            if n == 0:
                print('No unread messages.')
            else:
                print(f'You have {{n}} unread message(s). Run: board read')
        except Exception as e:
            print(f'Error checking messages: {{e}}')
        " 2>/dev/null || echo "No unread messages (API unreachable)."
                ;;

            team)
                echo "Team members are listed in the DRAFT_TEAM_ROSTER environment variable."
                echo ""
                echo "$DRAFT_TEAM_ROSTER"
                ;;

            all)
                api_call GET "$API/boards/$BOARD_ID/messages/all?ticket_id=$TICKET_ID" | python3 -c "
        import json,sys
        try:
            msgs = json.load(sys.stdin)
            if not msgs:
                print('No messages yet.')
            else:
                for m in msgs:
                    role = m.get('sender_role', '?')
                    content = m.get('content', '')
                    ts = m.get('created_at', '')[:19]
                    print(f'[{{ts}}] [{{role}}]: {{content}}')
                print(f'--- {{len(msgs)}} total message(s) ---')
        except Exception as e:
            print(f'Error reading messages: {{e}}')
        " 2>/dev/null || echo "No messages (API unreachable)."
                ;;

            help|--help|-h)
                usage
                ;;

            *)
                echo "Unknown command: $1"
                usage
                exit 1
                ;;
        esac
    """)


def inject_board_cli(
    worktree_path: Path,
    api_base_url: str = "http://localhost:8000",
) -> Path:
    """Write the board CLI script into a worktree's .draft/ directory.

    Returns the path to the generated script.
    """
    draft_dir = worktree_path / ".draft"
    draft_dir.mkdir(parents=True, exist_ok=True)

    cli_path = draft_dir / "board-cli.sh"
    cli_path.write_text(generate_board_cli_script(api_base_url))

    # Make executable
    cli_path.chmod(cli_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    # Also create a 'board' symlink for convenience
    board_link = draft_dir / "board"
    if board_link.exists() or board_link.is_symlink():
        board_link.unlink()
    board_link.symlink_to("board-cli.sh")

    logger.info("Board CLI injected at %s", cli_path)
    return cli_path
