#!/bin/bash
# =============================================================================
# Alma Kanban - Create Goal & Generate Report
# =============================================================================
# This script:
#   1. Creates a new goal
#   2. Generates tickets using AI
#   3. Accepts the tickets
#   4. Exports everything to a markdown file
#
# Usage:
#   ./scripts/create_goal_report.sh "Goal title" "Goal description"
#   ./scripts/create_goal_report.sh "Goal title" "Goal description" output.md
#
# Requirements:
#   - Backend running at localhost:8000
#   - jq installed (for JSON parsing)
# =============================================================================

set -e

API_URL="${API_URL:-http://localhost:8000}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}ℹ ${NC}$1"; }
log_success() { echo -e "${GREEN}✓ ${NC}$1"; }
log_warn() { echo -e "${YELLOW}⚠ ${NC}$1"; }
log_error() { echo -e "${RED}✗ ${NC}$1"; }

# Check dependencies
if ! command -v jq &> /dev/null; then
    log_error "jq is required. Install with: brew install jq"
    exit 1
fi

if ! curl -s "${API_URL}/health" > /dev/null 2>&1; then
    log_error "API not running at ${API_URL}. Start with: make dev-backend"
    exit 1
fi

log_success "Connected to API at ${API_URL}"

# Parse arguments
GOAL_TITLE="${1:-}"
GOAL_DESCRIPTION="${2:-}"
OUTPUT_FILE="${3:-}"

if [ -z "$GOAL_TITLE" ]; then
    echo -e "${YELLOW}Enter goal details:${NC}"
    read -p "Goal title: " GOAL_TITLE
    read -p "Goal description: " GOAL_DESCRIPTION
fi

if [ -z "$GOAL_TITLE" ]; then
    log_error "Goal title is required"
    exit 1
fi

# Generate default output filename from title
if [ -z "$OUTPUT_FILE" ]; then
    # Convert title to filename-safe format
    SAFE_TITLE=$(echo "$GOAL_TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
    OUTPUT_FILE="${SAFE_TITLE}-plan.md"
fi

# =============================================================================
# Step 1: Create the goal
# =============================================================================
echo ""
log_info "Creating goal: ${GOAL_TITLE}"

GOAL_RESPONSE=$(curl -s -X POST "${API_URL}/goals" \
    -H "Content-Type: application/json" \
    -d "{
        \"title\": $(echo "$GOAL_TITLE" | jq -Rs .),
        \"description\": $(echo "$GOAL_DESCRIPTION" | jq -Rs .)
    }")

GOAL_ID=$(echo "$GOAL_RESPONSE" | jq -r '.id')

if [ "$GOAL_ID" == "null" ] || [ -z "$GOAL_ID" ]; then
    log_error "Failed to create goal"
    echo "$GOAL_RESPONSE" | jq .
    exit 1
fi

GOAL_CREATED_AT=$(echo "$GOAL_RESPONSE" | jq -r '.created_at')
log_success "Created goal: ${GOAL_ID}"

# =============================================================================
# Step 2: Generate tickets
# =============================================================================
echo ""
log_info "Generating tickets for goal..."
log_warn "This may take 30-60 seconds (LLM call)"

TICKETS_RESPONSE=$(curl -s -X POST "${API_URL}/goals/${GOAL_ID}/generate-tickets" \
    -H "Content-Type: application/json" \
    -d '{"include_readme": true}')

# Check for error
if echo "$TICKETS_RESPONSE" | jq -e '.detail' > /dev/null 2>&1; then
    log_error "Failed to generate tickets:"
    echo "$TICKETS_RESPONSE" | jq .
    exit 1
fi

TICKET_COUNT=$(echo "$TICKETS_RESPONSE" | jq '.tickets | length')
log_success "Generated ${TICKET_COUNT} tickets"

# =============================================================================
# Step 3: Accept tickets
# =============================================================================
echo ""
log_info "Accepting ${TICKET_COUNT} tickets..."

TICKET_IDS_JSON=$(echo "$TICKETS_RESPONSE" | jq '[.tickets[].id]')

ACCEPT_RESPONSE=$(curl -s -X POST "${API_URL}/tickets/accept" \
    -H "Content-Type: application/json" \
    -d "{\"ticket_ids\": ${TICKET_IDS_JSON}}")

ACCEPTED=$(echo "$ACCEPT_RESPONSE" | jq '.accepted_count')
log_success "Accepted ${ACCEPTED} tickets"

# =============================================================================
# Step 4: Generate markdown report
# =============================================================================
echo ""
log_info "Generating markdown report: ${OUTPUT_FILE}"

# Start building the markdown
cat > "$OUTPUT_FILE" << EOF
# ${GOAL_TITLE}

> Generated by Alma Kanban on $(date '+%Y-%m-%d %H:%M:%S')

## Goal Details

- **ID:** \`${GOAL_ID}\`
- **Created:** ${GOAL_CREATED_AT}

### Description

${GOAL_DESCRIPTION}

---

## Tickets (${TICKET_COUNT} total)

EOF

# Add each ticket
echo "$TICKETS_RESPONSE" | jq -r '.tickets[] | @base64' | while read -r ticket_b64; do
    ticket=$(echo "$ticket_b64" | base64 -d)
    
    title=$(echo "$ticket" | jq -r '.title')
    description=$(echo "$ticket" | jq -r '.description')
    priority=$(echo "$ticket" | jq -r '.priority')
    priority_bucket=$(echo "$ticket" | jq -r '.priority_bucket')
    priority_rationale=$(echo "$ticket" | jq -r '.priority_rationale // empty')
    ticket_id=$(echo "$ticket" | jq -r '.id')
    notes=$(echo "$ticket" | jq -r '.notes // empty')
    
    # Get verification commands
    verification=$(echo "$ticket" | jq -r '.verification // [] | .[]' 2>/dev/null || echo "")
    
    cat >> "$OUTPUT_FILE" << TICKET_EOF

### ${priority_bucket}: ${title}

- **Priority:** ${priority} (${priority_bucket})
- **Ticket ID:** \`${ticket_id}\`
TICKET_EOF

    if [ -n "$priority_rationale" ]; then
        echo "- **Rationale:** ${priority_rationale}" >> "$OUTPUT_FILE"
    fi

    cat >> "$OUTPUT_FILE" << TICKET_EOF

#### Description

${description}

TICKET_EOF

    if [ -n "$verification" ]; then
        echo "#### Verification Commands" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo '```bash' >> "$OUTPUT_FILE"
        echo "$ticket" | jq -r '.verification // [] | .[]' >> "$OUTPUT_FILE"
        echo '```' >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi

    if [ -n "$notes" ]; then
        echo "#### Notes" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "${notes}" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi

    echo "---" >> "$OUTPUT_FILE"
done

# Add footer with commands
cat >> "$OUTPUT_FILE" << EOF

## Next Steps

1. **Start the planner** to begin automatic execution:
   \`\`\`bash
   curl -X POST ${API_URL}/planner/start
   \`\`\`

2. **View the board** in the UI:
   - Open http://localhost:5173

3. **Monitor progress** via API:
   \`\`\`bash
   curl ${API_URL}/board | jq
   \`\`\`

---

*Goal ID: \`${GOAL_ID}\`*
EOF

log_success "Report saved to: ${OUTPUT_FILE}"

# =============================================================================
# Summary
# =============================================================================
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Goal Created Successfully!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Goal ID:     ${GOAL_ID}"
echo "Tickets:     ${TICKET_COUNT} (in 'planned' state)"
echo "Report:      ${OUTPUT_FILE}"
echo ""
echo "Quick commands:"
echo "  View report:    cat ${OUTPUT_FILE}"
echo "  Start planner:  curl -X POST ${API_URL}/planner/start"
echo "  Open UI:        open http://localhost:5173"
echo ""


