"""add_normalized_log_entries

Revision ID: 8ef5054dc280
Revises: 014
Create Date: 2026-01-12 10:47:40.188826

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ef5054dc280"
down_revision: str | None = "014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create normalized_log_entries table
    op.create_table(
        "normalized_log_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum(
                "THINKING",
                "FILE_EDIT",
                "FILE_CREATE",
                "FILE_DELETE",
                "COMMAND_RUN",
                "TOOL_CALL",
                "ERROR",
                "USER_MESSAGE",
                "SYSTEM_MESSAGE",
                "LOADING",
                name="logentrytype",
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("entry_metadata", sa.JSON(), nullable=True),
        sa.Column("collapsed", sa.Boolean(), nullable=True, default=False),
        sa.Column("highlight", sa.Boolean(), nullable=True, default=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_normalized_log_entries_job_id", "normalized_log_entries", ["job_id"]
    )
    op.create_index(
        "ix_normalized_log_entries_job_sequence",
        "normalized_log_entries",
        ["job_id", "sequence"],
    )
    op.create_index(
        "ix_normalized_log_entries_entry_type", "normalized_log_entries", ["entry_type"]
    )

    op.drop_index(op.f("ix_agent_sessions_agent_type"), table_name="agent_sessions")
    op.drop_index(op.f("ix_agent_sessions_created_at"), table_name="agent_sessions")
    with op.batch_alter_table("boards") as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.create_foreign_key(
            "fk_jobs_source_revision_id",
            "revisions",
            ["source_revision_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.drop_column("agent_session_id")
        batch_op.drop_column("agent_type")
    op.drop_index(
        op.f("ix_review_comments_revision_resolved"), table_name="review_comments"
    )
    op.drop_index(
        op.f("ix_review_summaries_revision_id"), table_name="review_summaries"
    )
    op.create_index(
        op.f("ix_review_summaries_revision_id"),
        "review_summaries",
        ["revision_id"],
        unique=True,
    )
    with op.batch_alter_table("tickets") as batch_op:
        batch_op.drop_column("total_cost_usd")
    op.drop_index(op.f("ix_workspaces_ticket_id"), table_name="workspaces")
    op.create_index(
        op.f("ix_workspaces_ticket_id"), "workspaces", ["ticket_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop normalized_log_entries table
    op.drop_index(
        "ix_normalized_log_entries_entry_type", table_name="normalized_log_entries"
    )
    op.drop_index(
        "ix_normalized_log_entries_job_sequence", table_name="normalized_log_entries"
    )
    op.drop_index(
        "ix_normalized_log_entries_job_id", table_name="normalized_log_entries"
    )
    op.drop_table("normalized_log_entries")

    op.drop_index(op.f("ix_workspaces_ticket_id"), table_name="workspaces")
    op.create_index(
        op.f("ix_workspaces_ticket_id"), "workspaces", ["ticket_id"], unique=False
    )
    with op.batch_alter_table("tickets") as batch_op:
        batch_op.add_column(sa.Column("total_cost_usd", sa.FLOAT(), nullable=True))
    op.drop_index(
        op.f("ix_review_summaries_revision_id"), table_name="review_summaries"
    )
    op.create_index(
        op.f("ix_review_summaries_revision_id"),
        "review_summaries",
        ["revision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_comments_revision_resolved"),
        "review_comments",
        ["revision_id", "resolved"],
        unique=False,
    )
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.add_column(
            sa.Column("agent_type", sa.VARCHAR(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("agent_session_id", sa.VARCHAR(length=36), nullable=True)
        )
        batch_op.drop_constraint("fk_jobs_source_revision_id", type_="foreignkey")
    with op.batch_alter_table("boards") as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
    op.create_index(
        op.f("ix_agent_sessions_created_at"),
        "agent_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_agent_type"),
        "agent_sessions",
        ["agent_type"],
        unique=False,
    )
    # ### end Alembic commands ###
